<?php

/**
     * Implements hook_services_resources().
     */
    function afi_ws_ninho_services_resources() {
      return array(
       'ninho' => array(
         'retrieve' => array(
           'help' => 'Retrieves a ninho',
           'file' => array('type' => 'inc', 'module' => 'afi_ws_ninho', 'name' => 'afi_ws_ninho'),
           'callback' => '_afi_ws_ninho_retrieve',
           'args' => array(
             array(
               'name' => 'id',
               'type' => 'int',
               'description' => 'The id of the ninho to get',
               'source' => array('path' => '0'),
               'optional' => FALSE,
             ),
           ),
           'access arguments' => array('view'),
           'access arguments append' => FALSE,
         ),
         'create' => array(
           'help' => 'Creates a ninho',
           'file' => array('type' => 'inc', 'module' => 'afi_ws_ninho', 'name' => 'afi_ws_ninho'),
           'callback' => '_afi_ws_ninho_create',
           'access arguments' => array('access content'),
           'access arguments append' => FALSE,
           'args' => array(
             array(
               'name' => 'data',
               'type' => 'struct',
               'description' => 'The ninho object',
               'source' => 'data',
               'optional' => FALSE,
             ),
           ),
         ),
         'update' => array(
           'help' => 'Updates a ninho',
           'file' => array('type' => 'inc', 'module' => 'afi_ws_ninho', 'name' => 'afi_ws_ninho'),
           'callback' => '_afi_ws_ninho_update',
           'access callback' => '_afi_ws_ninho_access',
           'access arguments' => array('update'),
           'access arguments append' => TRUE,
           'args' => array(
             array(
               'name' => 'id',
               'type' => 'int',
               'description' => 'The id of the ninho to update',
               'source' => array('path' => '0'),
               'optional' => FALSE,
             ),
             array(
               'name' => 'data',
               'type' => 'struct',
               'description' => 'The ninho data object',
               'source' => 'data',
               'optional' => FALSE,
             ),
           ),
         ),
         'delete' => array(
           'help' => 'Deletes a ninho',
           'file' => array('type' => 'inc', 'module' => 'afi_ws_ninho', 'name' => 'afi_ws_ninho'),
           'callback' => '_afi_ws_ninho_delete',
           'access callback' => '_afi_ws_ninho_access',
           'access arguments' => array('delete'),
           'access arguments append' => TRUE,
           'args' => array(
             array(
               'name' => 'nid',
               'type' => 'int',
               'description' => 'The id of the ninho to delete',
               'source' => array('path' => '0'),
               'optional' => FALSE,
             ),
           ),
         ),
         'index' => array(
           'help' => 'Retrieves a listing of ninhos',
           'file' => array('type' => 'inc', 'module' => 'afi_ws_ninho', 'name' => 'afi_ws_ninho'),
           'callback' => '_afi_ws_ninho_index',
           'access arguments' => array('view'),
           'access arguments append' => FALSE,
           'args' => array(array(
               'name' => 'page',
               'type' => 'int',
               'description' => '',
               'source' => array(
                 'param' => 'page',
               ),
               'optional' => TRUE,
               'default value' => 0,
             ),
             array(
               'name' => 'parameters',
               'type' => 'array',
               'description' => '',
               'source' => 'param',
               'optional' => TRUE,
               'default value' => array(),
             ),
           ),
         ),
       ),
      );
    }

?>